POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Andrey Allyson",
  "email": "invitedd3@email.com",
  "referrer": "90a68085-0a92-4333-90ee-f88b5fb0f886"
}

###

GET http://localhost:3333/invites/90a68085-0a92-4333-90ee-f88b5fb0f886


###


GET http://localhost:3333/subscriptions/90a68085-0a92-4333-90ee-f88b5fb0f886/ranking/clicks

###


GET http://localhost:3333/ranking